apiVersion: v1
kind: Service
metadata:
  labels:
    app: updater-demo
    app.kubernetes.io/name: updater-demo
  name: updater-demo
spec:
  selector:
    app: updater-demo
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
