apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: add-ons
spec:
  project: default
  source:
    path: add-ons
    repoURL: https://github.com/pacoguzman/gitops
  destination:
    namespace: add-ons
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
