apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: devx
spec:
  project: default
  source:
    path: devx
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: devx
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
