

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-stack
spec:
  project: default
  source:
    path: kube-prometheus-stack
    repoURL: https://github.com/argoproj/argoproj-deployments
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-prometheus-stack
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /metadata/annotations
    - /metadata/labels
    - /spec/validation
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
