apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: routing
spec:
  project: default
  source:
    path: routing
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: routing
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    - ApplyOutOfSyncOnly=true
