apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
spec:
  source:
    path: sealed-secrets
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: sealed-secrets
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
