apiVersion: apps/v1
kind: Deployment
metadata:
  name: rollout-demo
  namespace: rollout-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rollout-demo
  template:
    metadata:
      labels:
        app: rollout-demo
    spec:
      containers:
        - name: rollout-demo
          image: argoproj/rollouts-demo:blue
          ports:
          - name: http
            containerPort: 8080
            protocol: TCP
          resources:
            requests:
              memory: 32Mi
              cpu: 5m
            limits:
              memory: 64Mi
              cpu: 50m
