apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: new-image
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: devx/new-image
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: new-application
  destination:
    server: https://kubernetes.default.svc
    namespace: new-image
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
