apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: updater-demo
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd-image-updater.argoproj.io/image-list: updater-demo=argoproj/rollouts-demo
    argocd-image-updater.argoproj.io/updater-demo.update-strategy: latest
    argocd-image-updater.argoproj.io/write-back-method: git
    argocd-image-updater.argoproj.io/git-branch: main
    # argocd-image-updater.argoproj.io/write-back-target: kustomization
spec:
  source:
    path: devx/updater-demo/prod
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: updater-demo
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
