apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vela-hello-world
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  source:
    path: devx/vela-hello-world
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
    #plugin:
    #  name: "vela"
  destination:
    server: https://kubernetes.default.svc
    namespace: vela-hello-world
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
