apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: digitalocean-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgB0FPR9rbdhQduq7H12HuKQgCyJdqK2qkeDGWMzGbfX3AMJErx4WiS1q/+WEA55D5p2E2rWUD0mwPQ3zLmMfXd60rKX4kewVFypbA8q2UWmvq3LN690EeD2vaKO/67MDQZHjkNL/Ts7BL99tbVd3bllRgOXgMQLjjiY9p3/zynd+z+T04wGWEj0Ecb3st7JIiXDqi0SzBDKqPxQOUuddQGJ5z1IiL0NLfdPAXrZommUznflLk8CDlQgk2hr927vNJnxW30eVB1x2f/GMqa6pDyiaVlyb//4dbzPNJK3ClC+a/iTTTJfjAfw01fmR+g32ALztFK1SL46c27Ppn3atBhNBzzULkVXRepLnfpWcD1vWI3pdSdD/WLGfNIe8pK49cpGt9eiCkGkuTQsfFMdE4MqNM33reaW9y1eIONBmwWdiy9mnOEpxEJaztmQQPfTFuOrDeOrkK8vviRVgLoNVxtg718cmAmmkg7PmAd1CsSRApXd0LCOPIMjLrWzJvMgd7PjrGjfnQNJRowRNs0qpL78sCeYKybG/ehtH7nddveAkZY093QQlGZGcScHwhtwZYqjCboqR537MOUZ8S5wJz24hm/C577ekDas0NmKA58tHevp3iACz7FVgnEqpbC3/QE3iL6mi8oSHAPAt7M257wt0tIsSZO5aGcaypeIwdcsl+bIyzcz9qJYTb9YxeUSA+omJwPXRF9sZCASezhQlhvQtpt1bOuiVBjT/WPv6dlQCk3Wfhrh+pRXHdMzZNaSa5fD7FvIsehNq8d9Yrs0P1j4Fg==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: digitalocean-secret
      namespace: default
    type: Opaque

