apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
spec:
  project: default
  source:
    path: add-ons/cert-manager
    repoURL: https://github.com/pacoguzman/gitops
  destination:
    namespace: cert-manager
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
