apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dex
spec:
  project: default
  source:
    path: add-ons/dex
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    namespace: dex
    server: https://kubernetes.default.svc
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
