apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: governor
spec:
  project: default
  source:
    path: add-ons/governor
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    namespace: governor
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
