apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istio-operator
spec:
  project: default
  source:
    repoURL: https://github.com/istio/istio
    path: manifests/charts/istio-operator
    targetRevision: release-1.13
    helm:
      parameters:
      - name: enableCRDTemplates
        value: 'true'
  destination:
    server: https://kubernetes.default.svc
    namespace: istio-operator
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
