apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
spec:
  project: default
  source:
    path: add-ons/kyverno
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    namespace: kyverno
    server: https://kubernetes.default.svc
  ignoreDifferences:
    - group: kyverno.io
      kind: ClusterPolicy
      managedFieldsManagers:
      - kyverno
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
