apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-adapter
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-adapter
    targetRevision: 3.0.2
  destination:
    namespace: prometheus-adapter
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: autoscaling
    kind: HorizontalPodAutoscaler
    jsonPointers:
    - /spec/metrics
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
