

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: prometheus-operator
spec:
  project: default
  source:
    path: add-ons/prometheus-operator
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: prometheus-operator
  ignoreDifferences:
  - group: apiextensions.k8s.io
    jsonPointers:
    - /metadata/annotations
    - /metadata/labels
    - /spec/validation
    kind: CustomResourceDefinition
  - group: admissionregistration.k8s.io
    kind: MutatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  - group: admissionregistration.k8s.io
    kind: ValidatingWebhookConfiguration
    jsonPointers:
    - /webhooks
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
