apiVersion: apps/v1
kind: Deployment
metadata:
  name: external-dns
spec:
  template:
    spec:
      containers:
      - name: external-dns
        env:
          - name: DO_TOKEN
            valueFrom:
              secretKeyRef:
                name: digitalocean-secret
                key: api-key
