apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/add-ons.yaml
##- base/jenkins.yaml
##- base/dex.yaml
# ArgoCD
##- base/argo-workflows.yaml
##- base/argo-events.yaml
- base/argo-cd.yaml
- base/argo-rollouts.yaml
##- base/argocd-image-updater.yaml
# Teams
- base/devx.yaml
- base/routing.yaml

namespace: argocd
