apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://raw.githubusercontent.com/kyverno/kyverno/v1.6.0/config/release/install.yaml
# Policies
- https://raw.githubusercontent.com/kyverno/policies/main/best-practices/require_pod_requests_limits/require_pod_requests_limits.yaml
- https://raw.githubusercontent.com/kyverno/policies/main/best-practices/disallow_latest_tag/disallow_latest_tag.yaml
- https://raw.githubusercontent.com/kyverno/policies/main/best-practices/check_deprecated_apis.yaml
