apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rollout-demo
spec:
  source:
    path: routing/rollout-demo
    repoURL: https://github.com/pacoguzman/gitops
    targetRevision: HEAD
  destination:
    server: https://fce6e581-b77e-42f5-86ad-134fa335a021.k8s.ondigitalocean.com
    namespace: default
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
