apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - overlays/production/digitalocean-sealedsecret.yaml
  - https://github.com/kubernetes-sigs/external-dns.git/kustomize?ref=v0.10.2

patches:
- path: overlays/production/deployment-env.yaml
  target:
    kind: Deployment
- path: overlays/production/deployment-args.yaml
  target:
    kind: Deployment
