apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- base/autoscale-demo.yaml
- base/autoscale-keda-demo.yaml
- base/updater-demo.yaml
- base/beta-updater-demo.yaml
#- base/backstage.yaml
- base/vela-hello-world.yaml

namespace: argocd
