apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - base/argo-cd-namespace.yaml
  - base/argo-cd-issuer.yaml
  - base/argo-cd-ui-ingress.yaml
  - base/rollouts-extension.yaml
  - https://raw.githubusercontent.com/argoproj/argo-cd/master/manifests/ha/install.yaml
  - overlays/production/dex-sealedsecret.yaml
  - overlays/production/vela-sealedsecret.yaml

components:
- https://github.com/argoproj-labs/argocd-extensions/manifests

patchesStrategicMerge:
- overlays/production/argo-cd-cm.yaml
- overlays/production/argocd-rbac-cm.yaml
- overlays/production/argocd-server-service.yaml
- overlays/production/argocd-repo-server-deploy.yaml
- overlays/production/argocd-notifications-controller-deploy.yaml
- overlays/production/argocd-notifications-cm.yaml
- https://raw.githubusercontent.com/argoproj/argo-cd/master/notifications_catalog/install.yaml

patchesJson6902:
- path: overlays/production/argocd-server-deploy-command.yaml
  target:
    group: apps
    kind: Deployment
    name: argocd-server
    version: v1

namespace: argocd

images:
- name: quay.io/argoproj/argocd
  newName: ghcr.io/argoproj/argocd
  newTag: 2.3.0-d4e9bdb0
