apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
data:
  application.resourceTrackingMethod: annotation
  # admin.enabled: 'false'
  statusbadge.enabled: 'true'
  users.anonymous.enabled: 'true'
  url: https://cd.gitops-do.pacoguzman.xyz
  configManagementPlugins: |
    - name: flux
      generate:
        command: [sh, -c]
        args: ["argocd-flux-plugin . --path $GIT_PATH"]
  dex.config: |
    logger:
      level: debug
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex-secret:dex.github.config.clientID
        clientSecret: $dex-secret:dex.github.config.clientSecret
        orgs:
        - name: pacoguzman-gitops
          teams:
          - admins
        teamNameField: slug
