apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.config.clientID: AgBKwFvWxEd12wgxOUbXNkD6teGENmWVC1/H5CUfJALYbPOQeZBCV0T+ZSv6SVYxDyrQa31duLgEAuDHXv2EN58BmqJkbEyi3odQfTwPTO3rTaCFEsZUfRm5brHhoI2TSCFNWLtBG5Q5ZRb8aO003to4u4UW32QF7WlOUxSv4iSLO2OVY4wunda77/vvD+eH5/kuM0Zf5gPu4NSSNZJkUUS9An8QPyNvkGfP5FjsNQimbekdQ3YfTVF7bJ38eKgsMZTW7Q96MmzUlUS8DC/4czWupE1LV3qxksisu1/fLOq11KGZz6FR/XIEIf3w7v6fw+q3B+Q5uKCfdNdEtXSxDtFN9Iq5YH6+V+aw4H4XPBqUdD/fdyBcoKT2FFDJQIHtbcOU9U10Qg7CuDjurUw1kXoArHgHF3vBIh31iWWDCR4u/zuq8W8CTnmbxgzgb9N9Ipcpg46D0LAAtwNdU9qx68j3Y2YAM29EweNBUhGdosVzZKVmXHNreArjLkxnF3bpNbelfDKIq2Ux0q/SgjNlfpn89We7Zb0NHtQH5lGF4yi5h0VBJmzB9O2zkpn61CJ3hQ90a87EVhaBCwmdSx+leQKxKSSYnpZ8f+nmGR+gYpHD+s33BY1lNj4Ucuf5RGHBhJeFvKXel4jJH3rNkjc5lNJd79lNeILbmjQPG8A6y1hpBax4kLBa6xjIxBPBPSyvKlPrtwf9rCsKSA2eWV+03bHHMymTsQ==
    dex.github.config.clientSecret: AgAqgiTO5xk6aARn1BDzx8Lx7sxtGBOZujmH6c7b3vRNnQxU4rk/V4N49YY01AO73fAp3aN8rbdfd+XJapC7pJ8WFNLwAc5QDzSDdl2x2hggWcV0PxnlQ3vFjx6MdzXv2hlGeTFdG6L+oXPhEOX4X6AQr6k+Q0PWIuC6HkST2jzE3aVpbuGvnzXUK2AXFZ+1Uj6VxVbjBJ21rT0w8RF2aenixK1V2tXz0P4gsVln/j5/VBukrQyBjQwLR0NKYLXu6oppFfenAXViPdLI9F9CB4XazGtqhHfRnDzAH3vhgw63eTnpkbCyq2Juy5TPFzzF8D9SdIJWqOevRGMXyDj7GJQu6FihR6CeX1UsX2lYq8EN4N0cBQdzGuG0HoX92nLYI4VdtBXKw2hQx+BOlK4A0m0VWPMm2R/v7VDIxfV03AoFoDN1zB6sQ8zFyaNL1XtcbmkrPlLnoMJMbyqaGiluejU3OMqlnpDD6eAlR+fcymWj3GAoDntvdJXJfbkInhFQJsCqnR2EsgMj3OsoZOXKopmpl5enwxpeSt+wNg+nXWVLOKMDfNnqmlw9RsJUxl15KJg+q3D1CvRM+twQvPk/+69XuYPzZvDULlQW7sw7mtIGWErwyNttpdBYTUeT4h8V6XqLFsXyLeo8GtRTl7M7Lp4JtHnMJ7ji03DhLpGZnQKCcFIJfy3qWh3FLGKLUwATRB30wjqIaXavnkK8uulr6uNG40aIjrK3pqWlD2BY88HK+/w73vmLwa9B
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dex-secret
        app.kubernetes.io/part-of: argocd
      name: dex-secret
      namespace: argocd
    type: Opaque

