apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.config.clientID: AgCPd3hh1vKae+b9+kX651H54IIkz2JfSajesvkDuNQiMXAxTBkKnMo7tZGnnXB+0CWTFm3TT/9hp8ROjMDHUhtNdcNTTzN9JotvfWhnBPbPsWwheG3yHi566Zw/W9Y0qpODUw9m1NwqJpgp/tAdEvmDs8j9OJpsWolaGPpza1Z2vCXaY+dnXcLHVQ1/Qkwl9QITFAfr4UNq2f308LE6Dg1Dsof7qhbdIZm50J8yJXbTj4u/11pOyfWbu7nfAwp+54XRwu4rL2rRTNQMnVUgcnyHH6em2isoza4Ut/w3XbBqxNGLavDcvSH0sMZIRK/dCQEW+UjNJIy5+XRF6+V80Stf97d9lpHzc7gdGjtoJsN3LiBhOydmgZQeS/Nbl8oMtbVEYxnu8ahJIYjsFDMzR6e2HRqMmvHu4OTmCrc2D/iaO8X/J5niMS9LKfZMrfZqkuxdcoXz8oz9DVZymMGUdsV7YnzwQ4YJ+YmWLYdLyd96J/ElJhgxhun5GrRdrOj3wfAkIK981Lbl2igbJp7gFAgwyfbH7MJ7IgYrGapC84LqjzvTE3xvY0/UdU4+dHfqjLozhMAPcqoa+AvAwql7c76LDmelPNedXeOhxvwK1kI/0QnUphY5rO8zm8+0IrzirHdYfewOfEa/iTWuavDVInlYWzZNhJ267FedEtb9ZcnNc8kS/xt/Mdl/bPPc8LcsqP95HkAXr6vueouBex/505QI+/MkHSgV4sSt1pRgpX6+Ziiwxyf0hVep
    dex.github.config.clientSecret: AgA2ar4/pGgZOHK7ytOOP7Q+VgH3wW5qcQ0A/v275XwNwVZ4nKvstzU/vhT0NZmoKYq5haCPW1oJyMVdWdIztomBzkhjvQ93cpI+yV+gSKeQ5qXKza/0VbeQqknna88ly51OunC99xNq/OxEghhfqoKPYyb8N9ypd39EMblBgJe2YTRtHyxcKucgWSR3eYYVmKMPV88jr3MTx99pSDvIN8SXMWgRB28cTjLM9PQ0yPGUsAXqXIJWjFLFDsSNJg1yvLQlrZfuhq9p9nSuGhY+CPlmwo0IR0vIbPnZtrM9rwBgl3rRbfQy3Nln6fs2rkIkBCMaIk2z/vt/izuuVJjKD6vdQTOS4chug6+2kX2NuL1+HqHbDsd8JPMZswHarmQ5g5j20nwURuuZspZtAInY6VchFsaFAUN1ybNoV+NABWKEQhc6DpzewmsOGQlXT1zgxvhIFg+bZbdh6zKWNLvw0Kp1M2qnMwoZfOcBM0t/jWATge4LvbsfKmhzJ9gnQTNIUU4EeGgRdDKAuBSMcVqbRsGdSpW1uM5a532wF8uU1XP+CVrF4avEx6s48EMk416u5P48EBkjBJkI+q4rofdPzEqF6Tx3pFAlEfCaSqHE3LGaRCfBFbrVzYJ9XRKD8d5c9OUo4qNAjgbW5ZjRel+j2DQbqSo7uFbU8zlB8/m7UgS1ido+q5HwHYDKkhHOQ5VF6m/sL7t0B72eBvH+IygqzYLR7EnRFw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dex-secret
        app.kubernetes.io/part-of: argocd
      name: dex-secret
      namespace: argocd
    type: Opaque

