apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: dex-secret
  namespace: argocd
spec:
  encryptedData:
    dex.github.config.clientID: AgCb15DBmt9qPnO7Sjh0rJ+ObYFsDeVKhQ70F51GMKj5gzJuBoTaUNoGjV5B+S3PvJ0ezmci8cUPmem9Blzo/1UqJsmG5z3drb5A2bqPDWLnhKWEFfHu8jZuB6q1TewdDTCODMJNF5lgsQdSyjqvTOpg+iW53WxFLpIjzUAVts60tYcTMiKdI9Rk2Nbz6+SBpXjZmqtE8AqaRtZvkigYEyYEBlLR4kRrbfcVBjWjtAbjjAhsIFNNceNEXFP9tJGKYw6kNXwKYX2RkU8EfMJg5AyJg/924sdJwbdmmjsapPg/KxNQd6HWFpbBYi5QpfF3EnbO6qjdtpTk/LnwrH4p8Yk2A3lc+o1MiFQtHs9/bmMaKhrJoj5BOCporWgY82WrJShj35XeVJrMkI+yxPqKVNAOJ4VrVTuJ5aJhDJGMkX741/OHKW1hOLH9lD7S6DyUfNmCVJgeTU0Y/dxroZiFMIG3VfH4J26RINEaFhTUqgDeTcX/DT0canKUyRZlAp7fmOjbLZV+hTo/nBBUmmbGMwjUjsALLakLTEiXZSl+7c/H8EckggTkYjHm4Pb9y0lHUYFI7tyaX89WO09T9zHrFmMrm9jxgaM4ud5U0qewUGjsKaTFKeY75zGTU9Q8M5NAaFPKdz9D1mpn5I2p19jMUgkJoBlJlxs4r6qmhGD6jPTWNoUteUxFsRYKh0+BrWuibELr/YV+GHquuG50rtxPxAVfZ8+wvA==
    dex.github.config.clientSecret: AgBoIvgUupPon81XsimdCUP4LoQD25wxAyC9iCOHkZZ7IUdrMRWJyqcSdB0YQdF594/0Sp5DIwKsUZb5wTi4O3gnS6VPMdE8huihlK1JduQXgJb4QEXfghyjywmeZZGoLxcDqMgHMTYo+EFBoKTbrN/a6DlEMtzpPw3zErKNjs1L+bYShhJ/OhcM1teI8U5w5lXPltqnpRBwHLDU3Jy+TTxwiP02MRNoyEOIQ/pOG3/YuJB44q37KZpBL9PfwJYsBhEELbXoJEAAtNVfhmA/18cI4z5NvpxzFxPQJohJFd/H0xqqzGCKVnKQ4GzoSHF5lJR+r70COTkT4bjlWrqweR6Tgv6tND3Q0qtVu9kzJ9LbiyLPCU7H936d0xvi+i12pbErTG5egBS4Jp1XlfDrrRBQrnIGKerw0Voe5CIxm/8VSmxqyqExaYvClnbAr0OSqQcwUoRsTokYMAmi1xanqqkgFaIWiYUCgibSOlsS2j8r280lxuCXqt95AK9M6LBBhp5usLIwCGQJnmarBTBJGFse0BiQy2ttctzNcdqZW4orhl7qVkhGYI+548YsJ67K4I8fhO0gD0//j1XCk4ZpCjaZPkAAikylwLT3AvpDk4ngp8yNw9n+jZBkNV92xbxJ6+Wj7sFfanf2QQ11w3arZ5bwqfRXgiRiRcOJgJlDATN6fqHaAXID5UaJpwPWOXB/BBfUx/G9xy7d/AN9Adx6ENQoI5PzIY7FoJ3VQKo3h0IHqdDAWYjeFsy4
  template:
    data: null
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: dex-secret
        app.kubernetes.io/part-of: argocd
      name: dex-secret
      namespace: argocd
    type: Opaque

