apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: sample-app
  labels:
    deploymentName: sample-app
spec:
  pollingInterval: 15
  cooldownPeriod:  30
  minReplicaCount: 1
  maxReplicaCount: 10
  scaleTargetRef:
    name: sample-app
  triggers:
  - type: prometheus
    metadata:
      serverAddress: "http://prometheus-operator-kube-p-prometheus.prometheus-operator.svc.cluster.local:9090"
      metricName: http_requests_total
      threshold: '50'
      query: sum(rate(http_requests_total{service="sample-app"}[2m]))
