apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-app
    app.kubernetes.io/name: sample-app
  name: sample-app
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '80'
    prometheus.io/path: '/metrics'
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: sample-app
  type: ClusterIP
