apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  "app.kubernetes.io/part-of": "dex"

resources:
  - dex-role.yaml
  - dex-sa.yaml
  - dex-rb.yaml
  - dex-deploy.yaml
  - dex-svc.yaml
  - dex-issuer.yaml
  - dex-ingress.yaml
