apiVersion: apps/v1
kind: Deployment
metadata:
  name: new-image
  labels:
    app: new-image
    app.kubernetes.io/name: new-image
spec:
  replicas: 1
  selector:
    matchLabels:
      app: new-image
  template:
    metadata:
      labels:
        app: new-image
    spec:
      containers:
      - image: luxas/autoscale-demo:v0.1.2
        name: metrics-provider
        ports:
        - name: http
          containerPort: 8080
