apiVersion: v1
kind: Service
metadata:
  labels:
    app: new-image
    app.kubernetes.io/name: new-image
  name: new-image
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: new-image
  type: ClusterIP
